apiVersion: tyk.tyk.io/v1
kind: Gateway
metadata:
  name: ahmets-gateway
spec:
  # Add fields here
  size: 1
  config:
    listen_port: 8000
    control_api_hostname: "/"
    control_api_port: 8001
    hostname: ""
    listen_address: "0.0.0.0"
    node_secret: abc
    secret: def
