name: Publish nightly

on:
  push:
    branches:
      - "master"
    paths:
      - "**.go"
      - "!hack/**"
jobs:
  publish_nightly_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt install curl jq
      - name: "publish nightly tag"
        if: success()
        env:
          TYK_OPERATOR_TOKEN: ${{ secrets.TYK_OPERATOR_TOKEN }}
        run: |
          tag=$(git for-each-ref --sort=-v:refname --count=1 --format '%(refname)' refs/tags/[0-9]*.[0-9]*.[0-9] refs/tags/v[0-9]*.[0-9]*.[0-9] | cut -d / -f 3-)
          tag_commit=$(git rev-list -n 1 $tag)
          commit=$(git rev-parse HEAD)
          commit_short=$(git rev-parse --short HEAD)
          new=$tag-nightly.$commit_short
          if [ "$tag_commit" == "$commit" ]; then
              echo "No new commits since previous tag. Skipping the tag creation..."
              exit 0
          fi
          dt=$(date '+%Y-%m-%dT%H:%M:%SZ')
          full_name=$GITHUB_REPOSITORY
          git_refs_url=$(jq .repository.git_refs_url $GITHUB_EVENT_PATH | tr -d '"' | sed 's/{\/sha}//g')
          echo "$dt: **pushing tag $new to repo $full_name"
          curl -s -X POST $git_refs_url \
          -H "Authorization: token $TYK_OPERATOR_TOKEN" \
          -d @- << EOF
          {
            "ref": "refs/tags/$new",
            "sha": "$commit"
          }
          EOF
