name: Tyk Pro Tests

on: pull_request

jobs:
  pro-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout tyk-operator
        uses: actions/checkout@v2
      - name: create kind cluster
        uses: helm/kind-action@v1.1.0
      - name: install kubebuilder
        uses: RyanSiu1995/kubebuilder-action@v1.1
        with:
          version: 2.3.1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: checking ci DASH_LICENSE expiry
        shell: bash
        run: jq -Re 'split(".")[1] | @base64d | fromjson | .exp > now' <<< "${{ secrets.DASH_LICENSE }}"
      - name: bootstrap tyk pro env
        shell: bash
        run: |
          export TYK_DB_LICENSEKEY=${{ secrets.DASH_LICENSE }}
          make boot-pro IMG=tykio/tyk-operator:test CLUSTER_NAME=chart-testing
      - name: bdd
        shell: bash
        run: |
          TYK_MODE=pro make test-all
